services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Repositories
  BenefitBundle\Repository\BenefitRepository: ~

  # Controllers
  BenefitBundle\Controller\Admin\BenefitCrudController: ~

  # Services
  BenefitBundle\Service\AdminMenu: ~